### ISSUE TITLE
Open in Tab no longer working correctly on macOS Sierra

### ISSUE THREAD

**Issue by idawgik** [fitztrev/shuttle#198]
I've been using Shuttle for a while now on El Capitan and it's been working great. I have a bunch of SSH sites configured to all open in a new tab in Terminal.app.

However, since I updated to Sierra the other day, this funcitonality is no longer working correctly.

If I have no terminal window open, then everything is fine when I select a site to open via Shuttle. However if I already have a terminal window open, then when i select a site via the Shuttle menu, it runs the command in the tab I currently have open and then opens a new tab that just sits there at the prompt. This causes issues since I might already be in another ssh session on the other tab and don't want the commands to be run there.

I'm guessing this has something to do with the changes to universal tabs in Sierra, but not sure.

Any help with this is appreciated.

Thanks!

**Comment by thshdw** [comment]
Hi @idawgik 
I have not installed macOS yet so I can't test. Are you using the latest [1.2.7](https://github.com/fitztrev/shuttle/releases/tag/v1.2.7)?

**Comment by helli72** [comment]
Can confirm this behavior and I use 1.2.7. Maybe it's possible to install macOS as a VM in VirtualBox?

**Comment by idawgik** [comment]
Hello, sorry I forgot the version info originally. Yes, I am using the latest 1.2.7 release. Everything was working fine with that version until I did the OS upgrade.

**Comment by thshdw** [comment]
@idawgik as a workaround could you see if ```"inTerminal": "new"``` is working. This would open your command in a new terminal. I understand that this is not ideal but perhaps this could get you by until I install macOS (probably this weekend)

**Comment by idawgik** [comment]
Setting it to `new` does work correctly, I'd actually already set a couple servers in my config to that to test. It's just the `tab` setting that isn't acting right.

And yes, I can get by with what I have until you're able to get it fixed :)

**Comment by thshdw** [comment]
@idawgik Thanks for the update.

**Comment by thshdw** [comment]
This should be fixed in v.1.2.8. Please comment if this is not the case.

**Comment by cbunyked** [comment]
hi. this issue still exist for me. I'm running zshrc (iterm2 build 3.0.10).

**Comment by thshdw** [comment]
@cbunyked You have this exact same issue? The original issue was Terminal.app was not working with tabs. I tested and confirmed this issue with Terminal.app... if you have iTerm then its this is probably a different issue. 

What is the issue with iTerm?

**Comment by bulolo** [comment]
same issue
